import streamlit as st
import requests
import datetime
import time

BASE_URL = "http://localhost:8000"  

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Header message
st.markdown("### 🧳 How can I help you plan a trip?\nLet me know where you want to go!")

# Input form
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("✍️ Enter your travel request", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("⏳ Generating your travel plan..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            
            st.markdown(f"""
### ✅ Travel Plan Generated

**🕒 Generated On:** `{datetime.datetime.now().strftime('%A, %d %B %Y • %I:%M %p')}`  
**🤖 Powered by:** *Himanshu's AI Travel Agent*

---

""")
            # Stream the output line-by-line (simulated)
            for line in answer.split("\n"):
                st.markdown(line)
                time.sleep(0.03)  # Simulate streaming delay

            st.markdown("""
---

❗ **Note:**  
> *This travel plan was generated by AI. Please verify all costs, timings, and travel rules before your journey.*
""")

        else:
            st.error("❌ Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"❌ An error occurred: {e}")
